### ISSUE TITLE
Missing new version v0.4.8 in dockerhub image repo

### ISSUE THREAD

**Issue by ctorrao** [xmidt-org/themis#103]
We noticed that the new release v0.4.8 of themis is not available in dockerhub image repositories. Is it supposed to not be there?

Dockerhub Repo: https://hub.docker.com/r/xmidt/themis/tags

**Comment by schmidtw** [comment]
I'll look into this.  I my have mistakenly dropped this.

**Comment by ctorrao** [comment]
I think we can close this, because feature releases are already in the GitHub Container Registry: https://github.com/xmidt-org/themis/pkgs/container/themis/versions
