### ISSUE TITLE
Updated README to align with other service READMEs

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/themis#23]
example:
https://github.com/xmidt-org/svalinn#svalinn

some things I've noticed:
- [x] Change `How to Install` to match `Build` and `Deploy` sections.
- [x] Add `Details` section.
- [x] Include examples in the `Details` section and get rid of `Usage`, or add examples to `Usage`.
- [ ] In the summary, link to XMiDT.
- [ ] In the summary, explain or link to an explanation of CPE.

**Comment by joe94** [comment]
@johnabass I remember you saying you were working on some themis documentation. Would that be something different than what is asked in this issue?

**Comment by joe94** [comment]
Closing this issue as documentation is added but will create a new one to copy the information elsewhere.
