### ISSUE TITLE
Error handling when `cpe_themis` fails to get claims from `rbl_themis`

### ISSUE THREAD

**Issue by joe94** [xmidt-org/themis#28]
Today, when `cpe_themis`  (`cpe`) encounters an error making an HTTP request to `rbl_themis` (`rbl`), the error message is not very helpful. For example, when the `rbl` URL was not configured correctly in `cpe_themis` we would see that while the internal error message in `cpe` is
```
Client sent an HTTP request to an HTTPS server.
```
`cpe` `/issue` endpoint consumers would see an error like:
```
invalid character 'C' looking for beginning of value
``` 
Notice that the API error grabs the first character of the internal error message.

`Note:` Similar errors occurred when the HTTP request method was flipped on the `cpe` side. Specifically, if the type was `GET` when `rbl` only had handlers for `POST`.

**Comment by johnabass** [comment]
This is now addressed by https://github.com/xmidt-org/themis/pull/29
