### ISSUE TITLE
Question: MSO Business Logic Connection

### ISSUE THREAD

**Issue by Equanox** [xmidt-org/themis#44]
In the architecture overview of xmidt (https://xmidt.io/assets/xmidt_core.png) CPE Auth is plotted. I've looked into the code of themis but could not find any mechanism/middleware to establish this connection or create a request if a CPE is allowed to issue a token.

Is my assumption correct that calling a MSOBL endpoint must be done in a reverse proxy or any other request-intercepting service before the request reaches the `/issue` endpoint of themis?

**Comment by joe94** [comment]
Hey @Equanox, thanks for your question! For the nature of the topic, do you mind reposting it in our discussions forum? https://discussion.xmidt.io/

**Comment by joe94** [comment]
Also, @Equanox we recently updated the readme at the front of this repo. Take a look in case any of it helps. We plan move some parts of the info there into https://xmidt.io/docs/operating/getting_started/ 

As you work through your project, we'd love to hear on how we could document our services better for the opensource community.

**Comment by joe94** [comment]
Closing this issue for now. Feel free to reopen if you see necessary.

**Comment by JC000** [comment]
@Equanox - I was hoping we could continue this discussion in a more appropriate forum.  The short answer to your question is that the MSOBL is meant to be implemented as a Themis plugin.
