### ISSUE TITLE
Add info on how to enable and configure mTLS

### ISSUE THREAD

**Issue by qthuy** [xmidt-org/themis#56]
Looking through the documentation, it is not clear how user enable and configure mTLS on themis. For example, how do I specify the CA/server certs and keys?

**Comment by Equanox** [comment]
AFAIK this is not part of themis and must be done before the requests hits themis. You can use a reverse-proxy like traefik or nginx for this.

**Comment by qthuy** [comment]
If mTLS is provided by another service like nginx/traefik, we can close this issue as resolve.

**Comment by johnabass** [comment]
Themis supports mTLS the same as another `golang` server.  You just need to configure the the relevant fields in `crypto/tls.Config`.

See: https://pkg.go.dev/crypto/tls?tab=doc#Config

In themis, you can set this via the configuration file:

```
servers:
    issuer:
        clientCACertificateFile: <path to certificate file or bundle>
```

When themis's bootstrap code see that field set, it automatically sets `crypto/tls.Config.ClientAuth` and `crypto/tls.Config.ClientCAs` appropriately.

**Comment by qthuy** [comment]
Ok, thank you for the info. Will give it a try.

**Comment by Equanox** [comment]
Thx, for clarification. Didn't know about it.

**Comment by visrey** [comment]
There is some serious information that is missing
you need to provide one more level of config which is missing.
I will post the update if someone bumped their head and looking for a solution.
