### ISSUE TITLE
Client certificate verification is broken

### ISSUE THREAD

**Issue by JC000** [xmidt-org/themis#91]
Certificate verification is broken if the client supplies an ICA in the request because of the parsing logic to determine the client's CN and SAN matches conditions we're expecting.

**Comment by johnabass** [comment]
What we want is: if *any* peer certificate passes custom validation, then the TLS connection is acceptable.  In other words, the client may submit any number of certificates with any trust relationship, but at least (1) must pass validation.

**Comment by JC000** [comment]
Fixed in [PR-92](https://github.com/xmidt-org/themis/pull/92)
